export const packageFeaturesEN = {
  website: {
    wordpress: {
      basic: [
        "Responsive professional design",
        "1 optimized page",
        "Contact form",
        "Speed optimization",
        "Social media integration",
        "Basic plugins installation",
        "Design adapted to your brand",
        "Ready to publish delivery",
      ],
      standard: [
        "Responsive professional design",
        "Up to 3 optimized pages",
        "Contact forms",
        "Basic SEO optimization",
        "Social media integration",
        "Design adapted to your brand",
        "Ready to publish delivery",
      ],
      premium: [
        "Responsive professional design",
        "Up to 5 optimized pages",
        "Advanced forms",
        "Complete SEO optimization",
        "Social media integration",
        "Google Analytics integration",
        "Design adapted to your brand",
        "Blog/news area",
        "Custom admin panel",
        "Training included",
      ],
    },
    custom: {
      basic: [
        "Responsive professional design",
        "1 page with HTML, CSS and JS",
        "Functional contact form",
        "Speed optimization",
        "Social media integration",
        "Use of TailwindCSS",
        "Basic animations",
        "Source code delivery",
      ],
      standard: [
        "Responsive professional design",
        "Up to 3 pages with HTML, CSS and JS",
        "Functional contact forms",
        "Speed and SEO optimization",
        "Social media integration",
        "Use of TailwindCSS",
        "Basic custom animations",
        "Clean and documented code",
        "Mobile device optimization",
        "Source code delivery",
      ],
      premium: [
        "Responsive professional design",
        "Up to 5 pages with HTML, CSS and JS",
        "Advanced forms with validation",
        "Advanced speed and SEO optimization",
        "Social media integration",
        "Third-party API integration",
        "React framework (optional)",
        "Advanced custom animations",
        "Clean, modular and documented code",
        "Optimization for all devices",
        "Source code delivery with documentation",
      ],
    },
  },
  ecommerce: {
    wordpress: {
      basic: [
        "Up to 50 products",
        "Template-based responsive design",
        "Product catalog",
        "Shopping cart",
        "Payment gateway",
        "Home page and categories",
        "Contact form",
        "Basic SEO optimization",
        "Essential plugins installation",
      ],
      standard: [
        "Up to 150 products",
        "Responsive professional design",
        "Catalog with filters",
        "Advanced shopping cart",
        "Payment gateways",
        "Basic shipping configuration",
        "Initial product import",
        "Complete SEO optimization",
        "Coupons and discounts",
        "Custom admin panel",
        "Documentation included",
      ],
      premium: [
        "Up to 300 products",
        "Custom premium design",
        "Advanced product filters",
        "Multiple payment gateways",
        "Tax configuration",
        "Complete shipping system",
        "Complete product import",
        "Membership/subscription system",
        "Advanced SEO optimization",
        "Advanced admin panel",
        "Speed analysis and optimization",
        "Video training",
      ],
    },
    shopify: {
      basic: [
        "Up to 50 products",
        "Optimized Shopify theme",
        "Product configuration",
        "Shopify payment gateway",
        "Basic shipping configuration",
        "Home page and collections",
        "Contact page",
        "Basic SEO optimization",
        "Domain configuration",
        "Note: Does not include monthly Shopify subscription",
      ],
      standard: [
        "Up to 150 products",
        "Advanced theme customization",
        "Product configuration with variants",
        "Advanced shipping configuration",
        "Initial product import",
        "Tax configuration",
        "Complete SEO optimization",
        "Domain and email configuration",
        "Essential apps installed and configured",
        "1 hour of training included",
        "Note: Does not include monthly Shopify subscription",
      ],
      premium: [
        "Up to 300 products",
        "Complete theme customization",
        "Custom design of key pages",
        "Advanced product configuration",
        "Multiple payment gateways",
        "Complete shipping system",
        "Complete product import with metadata",
        "Advanced SEO optimization",
        "Social media and marketing integration",
        "Premium apps installed and configured",
        "Conversion analysis and optimization",
        "2 hours of training included",
        "Note: Does not include monthly Shopify subscription",
      ],
    },
  },
};
