// Spanish package features
export const packageFeaturesES = {
  website: {
    wordpress: {
      basic: [
        "Diseño profesional responsive",
        "1 página optimizada",
        "Formulario de contacto",
        "Optimización de velocidad",
        "Integración con redes sociales",
        "Instalación de plugins básicos",
        "Diseño adaptado a tu marca",
        "Entrega lista para publicar",
      ],
      standard: [
        "Diseño profesional responsive",
        "Hasta 3 páginas optimizadas",
        "Formularios de contacto",
        "Optimización SEO básica",
        "Integración con redes sociales",
        "Diseño adaptado a tu marca",
        "Entrega lista para publicar",
      ],
      premium: [
        "Diseño profesional responsive",
        "Hasta 5 páginas optimizadas",
        "Formularios avanzados",
        "Optimización SEO completa",
        "Integración con redes sociales",
        "Integración con Google Analytics",
        "Diseño adaptado a tu marca",
        "Área de blog/noticias",
        "Panel de administración personalizado",
        "Capacitación incluida",
      ],
    },
    custom: {
      basic: [
        "Diseño profesional responsive",
        "1 página con HTML, CSS y JS",
        "Formulario de contacto funcional",
        "Optimización de velocidad",
        "Integración con redes sociales",
        "Uso de TailwindCSS",
        "Animaciones básicas",
        "Entrega de código fuente",
      ],
      standard: [
        "Diseño profesional responsive",
        "Hasta 3 páginas con HTML, CSS y JS",
        "Formularios de contacto funcionales",
        "Optimización de velocidad y SEO",
        "Integración con redes sociales",
        "Uso de TailwindCSS",
        "Animaciones personalizadas básicas",
        "Código limpio y documentado",
        "Optimización para dispositivos móviles",
        "Entrega de código fuente",
      ],
      premium: [
        "Diseño profesional responsive",
        "Hasta 5 páginas con HTML, CSS y JS",
        "Formularios avanzados con validación",
        "Optimización de velocidad y SEO avanzado",
        "Integración con redes sociales",
        "Integración con APIs de terceros",
        "Framework React (opcional)",
        "Animaciones personalizadas avanzadas",
        "Código limpio, modular y documentado",
        "Optimización para todos los dispositivos",
        "Entrega de código fuente con documentación",
      ],
    },
  },
  ecommerce: {
    wordpress: {
      basic: [
        "Hasta 50 productos",
        "Diseño responsive basado en platilla",
        "Catálogo de productos",
        "Carrito de compra",
        "Pasarela de pago",
        "Página de inicio y categorías",
        "Formulario de contacto",
        "Optimización básica SEO",
        "Instalación de plugins esenciales",
      ],
      standard: [
        "Hasta 150 productos",
        "Diseño profesional responsive",
        "Catálogo con filtros",
        "Carrito de compra avanzado",
        "Pasarelas de pago",
        "Configuración de envíos básica",
        "Importación inicial de productos",
        "Optimización SEO completa",
        "Cupones y descuentos",
        "Panel de administración personalizado",
        "Documentacion incluida",
      ],
      premium: [
        "Hasta 300 productos",
        "Diseño premium a medida",
        "Filtros avanzados de productos",
        "Múltiples pasarelas de pago",
        "Configuración de impuestos",
        "Sistema de envíos completo",
        "Importación completa de productos",
        "Sistema de membresías/suscripciones",
        "Optimización SEO avanzada",
        "Panel de administración avanzado",
        "Análisis de velocidad y optimización",
        "Capacitación en video",
      ],
    },
    shopify: {
      basic: [
        "Hasta 50 productos",
        "Tema Shopify optimizado",
        "Configuración de productos",
        "Pasarela de pago Shopify",
        "Configuración de envíos básica",
        "Página de inicio y colecciones",
        "Página de contacto",
        "Optimización básica SEO",
        "Configuración de dominio",
        "Nota: No incluye la suscripción mensual a Shopify",
      ],
      standard: [
        "Hasta 150 productos",
        "Personalización avanzada del tema",
        "Configuración de productos con variantes",
        "Configuración de envíos avanzada",
        "Importación inicial de productos",
        "Configuración de impuestos",
        "Optimización SEO completa",
        "Configuración de dominio y correos",
        "Apps esenciales instaladas y configuradas",
        "1 hora de capacitación incluida",
        "Nota: No incluye la suscripción mensual a Shopify",
      ],
      premium: [
        "Hasta 300 productos",
        "Personalización completa del tema",
        "Diseño personalizado de páginas clave",
        "Configuración avanzada de productos",
        "Múltiples pasarelas de pago",
        "Sistema de envíos completo",
        "Importación completa de productos con metadatos",
        "Optimización SEO avanzada",
        "Integración con redes sociales y marketing",
        "Apps premium instaladas y configuradas",
        "Análisis y optimización de conversión",
        "2 horas de capacitación incluidas",
        "Nota: No incluye la suscripción mensual a Shopify",
      ],
    },
  },
};
